### ISSUE TITLE
where is torch_dwt?

### ISSUE THREAD

**Issue by lijun2005** [wqlevi/DISGAN#1]
Hello! I have read your paper and you did a good job！When I tried to replicate your experiment, I couldn't find torch-dwt in the code, could you tell me where it is? Thank you very much!

**Comment by wqlevi** [comment]
Hi @lijun2005 , 

Thanks a lot for your attention!
I've added the link to this submodule `torch-dwt`. Could you please check again, see if you can import it after installing it? Thanks!

**Comment by lijun2005** [comment]
OK,I get it! Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wqlevi/DISGAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月16日(星期一) 凌晨3:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wqlevi/DISGAN] where is torch_dwt? (Issue #1)





 
Hi @lijun2005 ,
 
Thanks a lot for your attention!
 I've added the link to this submodule torch-dwt. Could you please check again, see if you can import it after installing it? Thanks!
